
Instrucciones

1. Transformación de Datos
*   Crea nuevas columnas: Basándonos en los datos existentes, crea nuevas columnas que sean útiles para el análisis. Por ejemplo, calcula el ingreso total por venta y normaliza las ventas.
*   Clasifica los datos: Crea una columna que clasifique las ventas en categorías significativas (e.g., ‘Alta’, ‘Media’, ‘Baja’).

2. Agrupación y Agregación
*   Agrupación por múltiples columnas: Realiza agrupaciones por categorías como producto y tienda, producto y mes, etc.
*   Aplicar funciones de agregación: Utiliza funciones como sum, mean, count, min, max, std, y var para obtener estadísticas descriptivas de cada grupo.

3. Análisis Personalizado con apply
*   Función personalizada: Aplica funciones personalizadas para realizar análisis específicos que no se pueden lograr con las funciones de agregación estándar.
*   Ejemplo de uso avanzado: Calcula la desviación de cada venta respecto a la media de su grupo

4. Documentación
Comentarios claros: Documenta claramente cada paso del análisis, explicando qué se hizo y por qué se hizo.
Código legible: Asegúrate de que el código sea legible y esté bien comentado.

In [1]:
# Usamos la biblioteca google para poder usar archivos en nuestro drive.
from google.colab import drive
# Este comando conecta colab con drive.
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# Importamos librerias.
import pandas as pd

In [3]:
# Importamos una bbdd en formato excel y lo guardamos en una variable.
path = "/content/drive/MyDrive/BBDD/Retail_sales.csv"
df = pd.read_csv(path)

In [4]:
# Visualizacion de la data cargada de 3 formas para mayir claridad.
df.info()

df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store ID               30000 non-null  object
 1   Product ID             30000 non-null  int64
 2   Date                   30000 non-null  object
 3   Units Sold             30000 non-null  int64
 4   Sales Revenue (USD)    30000 non-null  float64
 5   Discount Percentage    30000 non-null  int64
 6   Marketing Spend (USD)  30000 non-null  int64
 7   Store Location         30000 non-null  object
 8   Product Category       30000 non-null  object
 9   Day of the Week        30000 non-null  object
 10  Holiday Effect         30000 non-null  bool
dtypes: bool(1), float64(1), int64(4), object(5)
memory usage: 2.3+ MB

,Store ID,Product ID,Date,Units Sold,Sales Revenue (USD),Discount Percentage,Marketing Spend (USD),Store Location,Product Category,Day of the Week,Holiday Effect
0,Spearsland,52372247,2022-01-01,9,2741.69,20,81,Tanzania,Furniture,Saturday,False
1,Spearsland,52372247,2022-01-02,7,2665.53,0,0,Mauritania,Furniture,Sunday,False
2,Spearsland,52372247,2022-01-03,1,380.79,0,0,Saint Pierre and Miquelon,Furniture,Monday,False
3,Spearsland,52372247,2022-01-04,4,1523.16,0,0,Australia,Furniture,Tuesday,False
4,Spearsland,52372247,2022-01-05,2,761.58,0,0,Swaziland,Furniture,Wednesday,False

In [5]:
# Orden de la data sacando espacions y dejandola en minúsculas.
df.columns = df.columns.str.lower().str.strip()
df.head(5)

,store id,product id,date,units sold,sales revenue (usd),discount percentage,marketing spend (usd),store location,product category,day of the week,holiday effect
0,Spearsland,52372247,2022-01-01,9,2741.69,20,81,Tanzania,Furniture,Saturday,False
1,Spearsland,52372247,2022-01-02,7,2665.53,0,0,Mauritania,Furniture,Sunday,False
2,Spearsland,52372247,2022-01-03,1,380.79,0,0,Saint Pierre and Miquelon,Furniture,Monday,False
3,Spearsland,52372247,2022-01-04,4,1523.16,0,0,Australia,Furniture,Tuesday,False
4,Spearsland,52372247,2022-01-05,2,761.58,0,0,Swaziland,Furniture,Wednesday,False

In [6]:
# Revisar duplicados.
df[df.duplicated()]

Empty DataFrame
Columns: [store id, product id, date, units sold, sales revenue (usd), discount percentage, marketing spend (usd), store location, product category, day of the week, holiday effect]
Index: []

1. Transformación de Datos
- Crea nuevas columnas: Basándonos en los datos existentes, crea nuevas columnas que sean útiles para el análisis. Por ejemplo, calcula el ingreso total por venta y normaliza las ventas.

In [7]:
# Creamos la columna valor unotario para saber cuanto vende cada producto con descuento por volumen.
df["valor  unit"] = df["sales revenue (usd)"]  / df["units sold"]


# Creamos la columna Ingreso neto luego de aplicar el descuento.
df["net revenue"] = df["sales revenue (usd)"] * (1 - df["discount percentage"] / 100)

In [8]:
df.head(10)

,store id,product id,date,units sold,sales revenue (usd),discount percentage,marketing spend (usd),store location,product category,day of the week,holiday effect,valor unit,net revenue
0,Spearsland,52372247,2022-01-01,9,2741.69,20,81,Tanzania,Furniture,Saturday,False,304.632222,2193.352
1,Spearsland,52372247,2022-01-02,7,2665.53,0,0,Mauritania,Furniture,Sunday,False,380.790000,2665.530
2,Spearsland,52372247,2022-01-03,1,380.79,0,0,Saint Pierre and Miquelon,Furniture,Monday,False,380.790000,380.790
3,Spearsland,52372247,2022-01-04,4,1523.16,0,0,Australia,Furniture,Tuesday,False,380.790000,1523.160
4,Spearsland,52372247,2022-01-05,2,761.58,0,0,Swaziland,Furniture,Wednesday,False,380.790000,761.580
5,Spearsland,52372247,2022-01-06,8,3046.32,0,41,Bhutan,Furniture,Thursday,False,380.790000,3046.320
6,Spearsland,52372247,2022-01-07,6,2284.74,0,0,Suriname,Furniture,Friday,False,380.790000,2284.740
7,Spearsland,52372247,2022-01-08,9,3427.11,0,83,Taiwan,Furniture,Saturday,False,380.790000,3427.110
8,Spearsland,52372247,2022-01-09,7,2665.53,0,0,Papua New Guinea,Furniture,Sunday,False,380.790000,2665.530
9,Spearsland,52372247,2022-01-10,1,380.79,0,164,Canada,Furniture,Monday,False,380.790000,380.790

In [24]:
# Calculamos las columnas mean, std, median por producto.

df_estad_prod = df.groupby(["product id"])["sales revenue (usd)"].agg(["mean", "std", "median",]).round(2)
df_estad_prod

               mean      std   median
product id
3636541     5813.38  3023.43  5707.26
6741754     2311.18  1082.42  2307.55
8628619     6600.05  3523.92  6085.67
8914811     1606.11   866.16  1491.60
8978790     1338.85   684.73  1321.32
9189980     3211.21  1580.59  3177.06
9529489      342.09   171.09   337.50
14258596    5125.45  2878.87  4628.42
16840607    5113.32  2476.14  5205.06
18794205    3940.93  2295.87  3505.69
22286000     877.09   446.55   888.60
22571670     729.73   435.70   672.21
22928719     769.98   422.22   778.38
24102292    5305.80  3040.22  4747.00
29925957    3528.87  1903.34  3140.22
30776388    6593.25  3606.46  6112.32
34875230    3089.86  1522.22  3013.35
34892534     958.52   493.67   920.81
36491025    4832.35  2560.09  4265.94
38511400    2219.94  1066.42  2188.15
40024486    4142.10  2215.89  3757.89
44234706    1909.30   983.26  1867.20
47345331    3116.84  1735.74  2808.22
47856080    1217.11   662.12  1126.57
50239115    2803.88  1190.37  2501.15
52372247    2211.29  1143.37  2132.42
56183269    3538.66  1908.12  3301.94
56655933     327.13   167.36   285.55
60070623    3081.33  1528.90  3025.50
62375351    2322.95  1168.88  2236.20
64503400    1123.75   588.32  1083.06
65593523     963.60   454.51   957.85
65656938    5611.03  3207.11  5004.72
71215150    4644.54  2545.94  4375.67
73978756     921.61   519.70   822.30
80767985     207.02   112.19   182.28
81218219     364.08   179.53   372.00
86469371    4832.22  2532.30  4723.92
89528563    1305.86   653.04  1246.08
90008474    2063.84  1145.81  1795.32
93691949    2926.43  1536.10  2803.09
96282526    1589.09   755.26  1557.85

- Clasifica los datos: Crea una columna que clasifique las ventas en categorías significativas (e.g., ‘Alta’, ‘Media’, ‘Baja’)

In [ ]:
# Calcular total de ventas por vendedor.
# Primero se agrupa la data.
total_ventas = df.groupby("product id")["sales revenue (usd)"].sum()
print(total_ventas)

In [14]:
# Calcular total vendido por vendedor.
total_ventas = df.groupby("product id")["sales revenue (usd)"].sum()

# Función que devuelve la categoría según monto total de ventas.
def clasificar_por_ventas(productid):
    total = total_ventas[(productid)]
    if total > 1500000:
        return "Alta"
    elif total > 800000:
        return "Medio"
    else:
        return "Bajo"
# Se agrega la columna de categoría de vendedor.
df["Categoria"] = df["product id"].apply(clasificar_por_ventas)

# Mejor vendedor, por categoría
df_categ = df.groupby(["product id", "Categoria"])["sales revenue (usd)"].sum().round()
df_categ

product id  Categoria
3636541     Alta         4249578.0
6741754     Alta         1689473.0
8628619     Alta         4824635.0
8914811     Medio        1174068.0
8978790     Medio         978702.0
9189980     Alta         2347397.0
9529489     Bajo          250067.0
14258596    Alta         3746707.0
16840607    Alta         3737840.0
18794205    Alta         2880817.0
22286000    Bajo          641154.0
22571670    Bajo          533436.0
22928719    Bajo          562853.0
24102292    Alta         3878536.0
29925957    Alta         2579601.0
30776388    Alta         4819664.0
34875230    Alta         2258687.0
34892534    Bajo          700677.0
36491025    Alta         3532447.0
38511400    Alta         1622776.0
40024486    Alta         3027873.0
44234706    Medio        1395701.0
47345331    Alta         2278406.0
47856080    Medio         889710.0
50239115    Bajo           81312.0
52372247    Alta         1616453.0
56183269    Alta         2586763.0
56655933    Bajo          239133.0
60070623    Alta         2252454.0
62375351    Alta         1698077.0
64503400    Medio         821461.0
65593523    Bajo          704393.0
65656938    Alta         4101660.0
71215150    Alta         3395158.0
73978756    Bajo          673694.0
80767985    Bajo          151335.0
81218219    Bajo          266140.0
86469371    Alta         3532351.0
89528563    Medio         954580.0
90008474    Alta         1508667.0
93691949    Alta         2139222.0
96282526    Medio        1161626.0
Name: sales revenue (usd), dtype: float64

3. Agrupación y Agregación
- Agrupación por múltiples columnas: Realiza agrupaciones por categorías como producto y tienda, producto y mes, etc.

In [19]:
# Visualizamos la data para dar una idea general.
df.describe().T

,count,mean,std,min,25%,50%,75%,max
product id,30000.0,4.461294e+07,2.779759e+07,3636541.0,2.228600e+07,4.002449e+07,6.559352e+07,96282526.00
units sold,30000.0,6.161967e+00,3.323929e+00,0.0,4.000000e+00,6.000000e+00,8.000000e+00,56.00
sales revenue (usd),30000.0,2.749510e+03,2.568639e+03,0.0,8.825925e+02,1.902420e+03,3.863920e+03,27165.88
discount percentage,30000.0,2.973833e+00,5.974530e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,20.00
marketing spend (usd),30000.0,4.994403e+01,6.440165e+01,0.0,0.000000e+00,1.000000e+00,1.000000e+02,199.00
valor unit,29763.0,4.398867e+02,2.829559e+02,24.3,1.788200e+02,4.011767e+02,6.672960e+02,970.21
net revenue,30000.0,2.677840e+03,2.525556e+03,0.0,8.402480e+02,1.863500e+03,3.715596e+03,27165.88

In [20]:
# Visualizamos la data para dar una idea general.
df.head()

,store id,product id,date,units sold,sales revenue (usd),discount percentage,marketing spend (usd),store location,product category,day of the week,holiday effect,valor unit,net revenue,Categoria
0,Spearsland,52372247,2022-01-01,9,2741.69,20,81,Tanzania,Furniture,Saturday,False,304.632222,2193.352,Alta
1,Spearsland,52372247,2022-01-02,7,2665.53,0,0,Mauritania,Furniture,Sunday,False,380.790000,2665.530,Alta
2,Spearsland,52372247,2022-01-03,1,380.79,0,0,Saint Pierre and Miquelon,Furniture,Monday,False,380.790000,380.790,Alta
3,Spearsland,52372247,2022-01-04,4,1523.16,0,0,Australia,Furniture,Tuesday,False,380.790000,1523.160,Alta
4,Spearsland,52372247,2022-01-05,2,761.58,0,0,Swaziland,Furniture,Wednesday,False,380.790000,761.580,Alta

In [21]:
# Agrupamos por Store, localización, producto y contamos los tipos de producto que tiene cada tienda.
df.groupby(["store location", "product id"])["sales revenue (usd)"].sum()

store location  product id
Afghanistan     3636541       17121.78
                6741754       12068.49
                8914811        2147.90
                8978790        3897.89
                9189980        8445.68
                                ...
Zimbabwe        86469371      10943.75
                89528563       7403.79
                90008474      13704.28
                93691949      13548.25
                96282526       5919.83
Name: sales revenue (usd), Length: 9495, dtype: float64

In [22]:
# Productos que se vendieron por mes.

# separacion de fecha en Año_mes para poder ordenar.
df["date"] = pd.to_datetime(df["date"])
df["year_month"] = df["date"].dt.to_period('M').astype(str)

df.groupby(["year_month", "product id"])["sales revenue (usd)"].sum()

year_month  product id
2022-01     3636541       157758.20
            6741754        74095.44
            8628619       173828.11
            8914811        41705.14
            8978790        38098.06
                            ...
2024-01     86469371        2361.96
            89528563         415.36
            90008474        2393.76
            93691949        4204.63
            96282526         747.77
Name: sales revenue (usd), Length: 1026, dtype: float64

- Aplicar funciones de agregación: Utiliza funciones como sum, mean, count, min, max, std, y var para obtener estadísticas descriptivas de cada grupo.

In [25]:
# Para el 1er grupo se agregan  sum, mean, count, min, max, std.

df_estadisticas = df.groupby(["store location", "product id"])["sales revenue (usd)"].agg(["sum", "mean", "count", "min", "max", "std", "var",]).round(2)
df_estadisticas

                                sum     mean  count      min      max  \
store location product id
Afghanistan    3636541     17121.78  4280.44      4  1902.42  8560.89
               6741754     12068.49  2011.42      6   438.43  2769.06
               8914811      2147.90  1073.95      2   954.62  1193.28
               8978790      3897.89  1299.30      3   374.37  1981.98
               9189980      8445.68  2111.42      4   529.51  3150.58
...                             ...      ...    ...      ...      ...
Zimbabwe       86469371    10943.75  5471.88      2  3149.28  7794.47
               89528563     7403.79  1850.95      4  1381.07  2284.48
               90008474    13704.28  2284.05      6   598.44  5086.74
               93691949    13548.25  2709.65      5   519.09  4671.81
               96282526     5919.83  1973.28      3  1246.28  2804.13

                               std          var
store location product id
Afghanistan    3636541     2957.43   8746404.49
               6741754      842.74    710206.05
               8914811      168.76     28479.30
               8978790      830.73    690113.85
               9189980     1135.75   1289923.98
...                            ...          ...
Zimbabwe       86469371    3284.65  10788895.07
               89528563     369.41    136465.26
               90008474    1732.55   3001729.52
               93691949    1709.22   2921425.66
               96282526     784.10    614813.81

[9495 rows x 7 columns]

In [26]:
# Para el 2do grupo se agregan sum, mean, count, min, max, std.

df_mes = df.groupby(["year_month", "product id"])["sales revenue (usd)"].agg(["sum", "mean", "count", "min", "max", "std", "var",]).round(2)
df_mes

                             sum     mean  count      min       max      std  \
year_month product id
2022-01    3636541     157758.20  5088.97     31   903.65  11985.25  2564.95
           6741754      74095.44  2390.18     31   830.72   5538.12  1120.84
           8628619     173828.11  5607.36     31   965.98  11591.76  2618.96
           8914811      41705.14  1345.33     31   298.32   2147.90   557.53
           8978790      38098.06  1228.97     31   440.44   3083.08   544.71
...                          ...      ...    ...      ...       ...      ...
2024-01    86469371      2361.96  2361.96      1  2361.96   2361.96      NaN
           89528563       415.36   415.36      1   415.36    415.36      NaN
           90008474      2393.76  2393.76      1  2393.76   2393.76      NaN
           93691949      4204.63  4204.63      1  4204.63   4204.63      NaN
           96282526       747.77   747.77      1   747.77    747.77      NaN

                              var
year_month product id
2022-01    3636541     6578953.87
           6741754     1256285.81
           8628619     6858933.55
           8914811      310835.58
           8978790      296709.03
...                           ...
2024-01    86469371           NaN
           89528563           NaN
           90008474           NaN
           93691949           NaN
           96282526           NaN

[1026 rows x 7 columns]

Análisis Personalizado con apply
- Función personalizada: Aplica funciones personalizadas para realizar análisis específicos que no se pueden lograr con las funciones de agregación estándar.

In [27]:
# Funcion para evaluar si la venta fue rentable considerando marketing spend (usd).

def evaluar_rentabilidad(col):
    if col["marketing spend (usd)"] == 0:
        return "Sin inversión"
    elif col["sales revenue (usd)"] >= col["marketing spend (usd)"] * 3:
        return "Rentable"
    else:
        return "No rentable"

df["rentabilidad"] = df.apply(evaluar_rentabilidad, axis=1)
df.head()

,store id,product id,date,units sold,sales revenue (usd),discount percentage,marketing spend (usd),store location,product category,day of the week,holiday effect,valor unit,net revenue,Categoria,year_month,rentabilidad
0,Spearsland,52372247,2022-01-01,9,2741.69,20,81,Tanzania,Furniture,Saturday,False,304.632222,2193.352,Alta,2022-01,Rentable
1,Spearsland,52372247,2022-01-02,7,2665.53,0,0,Mauritania,Furniture,Sunday,False,380.790000,2665.530,Alta,2022-01,Sin inversión
2,Spearsland,52372247,2022-01-03,1,380.79,0,0,Saint Pierre and Miquelon,Furniture,Monday,False,380.790000,380.790,Alta,2022-01,Sin inversión
3,Spearsland,52372247,2022-01-04,4,1523.16,0,0,Australia,Furniture,Tuesday,False,380.790000,1523.160,Alta,2022-01,Sin inversión
4,Spearsland,52372247,2022-01-05,2,761.58,0,0,Swaziland,Furniture,Wednesday,False,380.790000,761.580,Alta,2022-01,Sin inversión

- Ejemplo de uso avanzado: Calcula la desviación de cada venta respecto a la media de su grupo

In [34]:
# Usando la funcion apply y calculando la media por columna.
# Desviación = venta individual−media de ventas del grupo.

df.groupby(["product id"])["sales revenue (usd)"].sum()

# asegurar que sales revenue sea numérico.
df["sales revenue (usd)"] = pd.to_numeric(df["sales revenue (usd)"], errors="coerce")

# Calcular la media de ventas por product id, transform('mean') te da un valor por cada fila, manteniendo el índice.
media_por_producto = df.groupby("product id")["sales revenue (usd)"].transform("mean")
df["media_por_producto"] = media_por_producto

# Calcular la desviación respecto a la media del producto.
df["desviacion_vs_media"] = df["sales revenue (usd)"] - media_por_producto

In [33]:
df.head()

,store id,product id,date,units sold,sales revenue (usd),discount percentage,marketing spend (usd),store location,product category,day of the week,holiday effect,valor unit,net revenue,Categoria,year_month,rentabilidad,desviacion_vs_media,media_por_producto
0,Spearsland,52372247,2022-01-01,9,2741.69,20,81,Tanzania,Furniture,Saturday,False,304.632222,2193.352,Alta,2022-01,Rentable,530.399371,2211.290629
1,Spearsland,52372247,2022-01-02,7,2665.53,0,0,Mauritania,Furniture,Sunday,False,380.790000,2665.530,Alta,2022-01,Sin inversión,454.239371,2211.290629
2,Spearsland,52372247,2022-01-03,1,380.79,0,0,Saint Pierre and Miquelon,Furniture,Monday,False,380.790000,380.790,Alta,2022-01,Sin inversión,-1830.500629,2211.290629
3,Spearsland,52372247,2022-01-04,4,1523.16,0,0,Australia,Furniture,Tuesday,False,380.790000,1523.160,Alta,2022-01,Sin inversión,-688.130629,2211.290629
4,Spearsland,52372247,2022-01-05,2,761.58,0,0,Swaziland,Furniture,Wednesday,False,380.790000,761.580,Alta,2022-01,Sin inversión,-1449.710629,2211.290629