1. Preparación del Entorno
Asegúrate de tener instalado Pandas en tu entorno de trabajo.
Descarga el archivo dataset.csv desde Kaggle. Elige un dataset que te interese y que no incluya visualización de datos. Algunas sugerencias pueden ser datasets relacionados con ventas, compras, productos, etc.
Archivo seleccionado Tesla-dataset.csv

In [40]:
# Usamos la biblioteca google para poder usar archivos en nuestro drive.
from google.colab import drive
# Este comando conecta colab con drive.
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

2. Cargar los Datos
Carga el archivo CSV en un DataFrame de Pandas.
Muestra las primeras 10 filas del DataFrame para confirmar que los datos se han cargado correctamente.

In [43]:
# Importamos librerias.
import pandas as pd

In [45]:
# Importamos una bbdd en formato excel y lo guardamos en una variable.
path = "/content/drive/MyDrive/BBDD/Chocolate Sales.csv"
df = pd.read_csv(path)

In [46]:
# Visualizamos el DataFrame.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094 entries, 0 to 1093
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   1094 non-null   object
 1   Country        1094 non-null   object
 2   Product        1094 non-null   object
 3   Date           1094 non-null   object
 4   Amount         1094 non-null   object
 5   Boxes Shipped  1094 non-null   int64
dtypes: int64(1), object(5)
memory usage: 51.4+ KB

In [47]:
# Visualizamos el DataFrame con 10 líneaas.
df.head(10)

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04-Jan-22,"$5,320",180
1,Van Tuxwell,India,85% Dark Bars,01-Aug-22,"$7,896",94
2,Gigi Bohling,India,Peanut Butter Cubes,07-Jul-22,"$4,501",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27-Apr-22,"$12,726",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24-Feb-22,"$13,685",184
5,Van Tuxwell,India,Smooth Sliky Salty,06-Jun-22,"$5,376",38
6,Oby Sorrel,UK,99% Dark & Pure,25-Jan-22,"$13,685",176
7,Gunar Cockshoot,Australia,After Nines,24-Mar-22,"$3,080",73
8,Jehu Rudeforth,New Zealand,50% Dark Bites,20-Apr-22,"$3,990",59
9,Brien Boise,Australia,99% Dark & Pure,04-Jul-22,"$2,835",102

3. Exploración Inicial de los Datos
Muestra las últimas 5 filas del DataFrame.
Utiliza el método info() para obtener información general sobre el DataFrame, incluyendo el número de entradas, nombres de las columnas, tipos de datos y memoria utilizada.
Genera estadísticas descriptivas del DataFrame utilizando el método describe().

In [48]:
# Visualizamos el DataFrame.
df.info()

# Visualizamos el DataFrame con 5 líneaas.
df.head(5)

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094 entries, 0 to 1093
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   1094 non-null   object
 1   Country        1094 non-null   object
 2   Product        1094 non-null   object
 3   Date           1094 non-null   object
 4   Amount         1094 non-null   object
 5   Boxes Shipped  1094 non-null   int64
dtypes: int64(1), object(5)
memory usage: 51.4+ KB

       Boxes Shipped
count    1094.000000
mean      161.797989
std       121.544145
min         1.000000
25%        70.000000
50%       135.000000
75%       228.750000
max       709.000000

4. Limpieza de Datos
Identifica y maneja los datos faltantes utilizando técnicas apropiadas (relleno con valores estadísticos, interpolación, eliminación, etc.).
Corrige los tipos de datos si es necesario (por ejemplo, convertir cadenas a fechas).
Elimina duplicados si los hay.

In [49]:
df.columns = df.columns.str.lower().str.strip()

In [50]:
df.info()
# Según lo revisado no se requiere limpieza de datos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094 entries, 0 to 1093
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   sales person   1094 non-null   object
 1   country        1094 non-null   object
 2   product        1094 non-null   object
 3   date           1094 non-null   object
 4   amount         1094 non-null   object
 5   boxes shipped  1094 non-null   int64
dtypes: int64(1), object(5)
memory usage: 51.4+ KB

In [51]:
df.head()

,sales person,country,product,date,amount,boxes shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04-Jan-22,"$5,320",180
1,Van Tuxwell,India,85% Dark Bars,01-Aug-22,"$7,896",94
2,Gigi Bohling,India,Peanut Butter Cubes,07-Jul-22,"$4,501",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27-Apr-22,"$12,726",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24-Feb-22,"$13,685",184

In [52]:
# Revisión de duplicados
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1089    False
1090    False
1091    False
1092    False
1093    False
Length: 1094, dtype: bool

In [53]:
# Revisar duplicados.
df.duplicated().sum()

np.int64(0)

In [54]:
# Revisar duplicados.
df[df.duplicated()]

Empty DataFrame
Columns: [sales person, country, product, date, amount, boxes shipped]
Index: []

In [64]:
# Cambiamos amout a .astype() para poder crear nuevas columnas.
# Limpiar la columna 'amount' y convertirla a int, se elimina $ y , del monto.
df['amount'] = df['amount'].replace('[\$,]', '', regex=True).astype(int)

In [71]:
# Verificamos el resultado
print(df[['amount', 'boxes shipped']].dtypes)
print(df)

amount           int64
boxes shipped    int64
dtype: object
          sales person    country              product       date  amount  \
0       Jehu Rudeforth         UK      Mint Chip Choco  04-Jan-22    5320
1          Van Tuxwell      India        85% Dark Bars  01-Aug-22    7896
2         Gigi Bohling      India  Peanut Butter Cubes  07-Jul-22    4501
3         Jan Morforth  Australia  Peanut Butter Cubes  27-Apr-22   12726
4       Jehu Rudeforth         UK  Peanut Butter Cubes  24-Feb-22   13685
...                ...        ...                  ...        ...     ...
1089  Karlen McCaffrey  Australia  Spicy Special Slims  17-May-22    4410
1090    Jehu Rudeforth        USA           White Choc  07-Jun-22    6559
1091      Ches Bonnell     Canada  Organic Choco Syrup  26-Jul-22     574
1092    Dotty Strutley      India              Eclairs  28-Jul-22    2086
1093  Karlen McCaffrey      India       70% Dark Bites  23-May-22    5075

      boxes shipped  Total_sales
0               180       957600
1                94       742224
2                91       409591
3               342      4352292
4               184      2518040
...             ...          ...
1089            323      1424430
1090            119       780521
1091            217       124558
1092            384       801024
1093            344      1745800

[1094 rows x 7 columns]

In [60]:
df.columns

Index(['sales person', 'country', 'product', 'date', 'amount', 'boxes shipped',
       'Total_sales'],
      dtype='object')

5. Transformación de Datos
Crea nuevas columnas basadas en operaciones con las columnas existentes (por ejemplo, calcular ingresos a partir de ventas y precios).
Normaliza o estandariza columnas si es necesario.
Clasifica los datos en categorías relevantes.

In [68]:
# Creamos la columna Total_sales para saber cuanto vende cada Verdedor.
df["Total_sales"] = df["amount"]  * df["boxes shipped"]

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094 entries, 0 to 1093
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   sales person   1094 non-null   object
 1   country        1094 non-null   object
 2   product        1094 non-null   object
 3   date           1094 non-null   object
 4   amount         1094 non-null   int64
 5   boxes shipped  1094 non-null   int64
 6   Total_sales    1094 non-null   int64
dtypes: int64(3), object(4)
memory usage: 60.0+ KB

In [72]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
amount,1094.0,5652.308044,4.102442e+03,7.0,2390.5,4868.5,8027.25,22050.0
boxes shipped,1094.0,161.797989,1.215441e+02,1.0,70.0,135.0,228.75,709.0
Total_sales,1094.0,905153.063071,1.041773e+06,588.0,186784.5,553980.0,1244832.75,6985888.0

In [69]:
df.head()

,sales person,country,product,date,amount,boxes shipped,Total_sales
0,Jehu Rudeforth,UK,Mint Chip Choco,04-Jan-22,5320,180,957600
1,Van Tuxwell,India,85% Dark Bars,01-Aug-22,7896,94,742224
2,Gigi Bohling,India,Peanut Butter Cubes,07-Jul-22,4501,91,409591
3,Jan Morforth,Australia,Peanut Butter Cubes,27-Apr-22,12726,342,4352292
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24-Feb-22,13685,184,2518040

In [73]:
# Vemos los paises donde se venten estos chocolates
df['country'].value_counts()

country
Australia      205
India          184
USA            179
UK             178
Canada         175
New Zealand    173
Name: count, dtype: int64

In [121]:
# Podemos revisar los chocolates mas vendidos por país.
df.groupby(["country", "product"]).size().sort_index()

country    product
Australia  50% Dark Bites         16
           70% Dark Bites          9
           85% Dark Bars           8
           99% Dark & Pure        11
           After Nines             7
                                  ..
USA        Peanut Butter Cubes     7
           Raspberry Choco        11
           Smooth Sliky Salty      8
           Spicy Special Slims     8
           White Choc             10
Length: 132, dtype: int64

In [132]:
# Producto mas vendido por país.
df.groupby(["product", "boxes shipped", "country"]).sum()

                                                 sales person       date  \
product        boxes shipped country
50% Dark Bites 6             Australia        Madelene Upcott  25-Jul-22
               10            New Zealand          Van Tuxwell  11-Jul-22
               12            Australia    Dennison Crosswaite  01-Apr-22
                             India            Roddy Speechley  14-Mar-22
               13            USA               Mallorie Waber  19-Apr-22
...                                                       ...        ...
White Choc     321           New Zealand          Brien Boise  15-Jun-22
               330           India             Dotty Strutley  15-Aug-22
               341           USA                 Ches Bonnell  11-Feb-22
               342           India             Curtice Advani  04-Jul-22
               370           Australia           Barr Faughny  04-Jul-22

                                          amount  Total_sales  mediana  \
product        boxes shipped country
50% Dark Bites 6             Australia      7350        44100   4868.5
               10            New Zealand    3626        36260   4868.5
               12            Australia      7287        87444   4868.5
                             India          8337       100044   4868.5
               13            USA            1736        22568   4868.5
...                                          ...          ...      ...
White Choc     321           New Zealand    5509      1768389   4868.5
               330           India         12327      4067910   4868.5
               341           USA            5271      1797411   4868.5
               342           India          7154      2446668   4868.5
               370           Australia      8113      3001810   4868.5

                                           Categoria
product        boxes shipped country
50% Dark Bites 6             Australia    Top Seller
               10            New Zealand  Top Seller
               12            Australia    Top Seller
                             India        Top Seller
               13            USA          Top Seller
...                                              ...
White Choc     321           New Zealand  Top Seller
               330           India        Top Seller
               341           USA          Top Seller
               342           India        Top Seller
               370           Australia    Top Seller

[1082 rows x 6 columns]

6. Análisis de Datos
Realiza agrupaciones de datos utilizando groupby para obtener insights específicos (por ejemplo, ventas por producto, ventas por región, etc.).
Aplica funciones de agregación como sum, mean, count, min, max, std, y var.
Utiliza el método apply para realizar operaciones más complejas y personalizadas.

In [98]:
# Muestra una comparación promedio, desviacion y mediana de precio y cantidades por pais.

dict_1 = {
  "amount": ["sum", "min", "max", "mean", "std", "median", "var"],
  "boxes shipped": ["sum", "min", "max", "mean", "std", "median", "var"]
}
df.groupby("country").agg(dict_1).round(2)

              amount                                                     \
                 sum  min    max     mean      std  median          var
country
Australia    1137367   63  19453  5548.13  3800.39  5194.0  14442943.50
Canada        962899  210  16793  5502.28  3888.96  4830.0  15124020.86
India        1045800   28  22050  5683.70  4362.83  4581.5  19034303.74
New Zealand   950418    7  19481  5493.75  3942.99  5061.0  15547196.74
UK           1051792    7  18991  5908.94  4176.18  5274.5  17440448.40
USA          1035349   70  17465  5784.07  4464.22  4802.0  19929228.06

            boxes shipped
                      sum min  max    mean     std median       var
country
Australia           32647   3  708  159.25  125.75  119.0  15813.87
Canada              31221   1  709  178.41  140.87  151.0  19842.96
India               29470   2  581  160.16  122.25  136.0  14944.86
New Zealand         26580   4  518  153.64  117.84  129.0  13886.70
UK                  30265   2  554  170.03  108.52  152.0  11776.11
USA                 26824   2  508  149.85  110.19  131.0  12141.50

In [130]:
# Calcular total vendido por persona
total_por_persona = df.groupby("sales person")["Total_sales"].sum()

# Función que devuelve la categoría según monto total de ventas
def clasificar_por_ventas(nombre):
    total = total_por_persona[nombre]
    if total > 15000000:
        return "Top Seller"
    elif total > 10000000:
        return "Medio"
    else:
        return "Bajo"
# Se agrega la columna de categoria de vendedor
df["Categoria"] = df["sales person"].apply(clasificar_por_ventas)

# Mejor vendedor, por categoria
df.groupby(["sales person", "Categoria"]).sum().sort_index()

,,country,product,date,amount,boxes shipped,Total_sales,mediana
sales person,Categoria,,,,,,,
Andria Kimpton,Top Seller,CanadaUKIndiaAustraliaAustraliaNew ZealandUSAC...,After Nines50% Dark BitesSpicy Special Slims50...,11-May-2224-Aug-2223-Feb-2202-Jun-2228-Jun-222...,201747,6448,31770956,189871.5
Barr Faughny,Top Seller,USAAustraliaUSAUSAAustraliaUKCanadaNew Zealand...,Orange ChocoFruit & Nut BarsRaspberry ChocoFru...,10-Mar-2230-Jun-2212-Apr-2228-Jan-2204-Jul-222...,258713,6366,37271192,209345.5
Beverie Moffet,Top Seller,AustraliaCanadaUSAAustraliaNew ZealandUKIndiaN...,Organic Choco SyrupMilk BarsRaspberry ChocoEcl...,26-Jan-2216-Feb-2219-Apr-2220-Jun-2224-Mar-223...,278922,9214,51179380,243425.0
Brien Boise,Top Seller,AustraliaAustraliaAustraliaCanadaNew ZealandCa...,99% Dark & PureEclairsFruit & Nut Bars99% Dark...,04-Jul-2227-Jun-2206-Jun-2218-May-2201-Aug-220...,312816,8102,52568747,258030.5
Camilla Castle,Top Seller,AustraliaIndiaUSAUSAAustraliaUKNew ZealandIndi...,85% Dark Bars50% Dark BitesSpicy Special Slims...,19-May-2204-Jul-2211-Feb-2218-Aug-2229-Apr-220...,196616,5374,33360705,155792.0
Ches Bonnell,Top Seller,New ZealandIndiaUKAustraliaAustraliaUKAustrali...,Spicy Special SlimsSpicy Special SlimsSmooth S...,14-Feb-2206-Jul-2211-Jul-2205-Jul-2202-Mar-222...,320901,7522,45304784,233688.0
Curtice Advani,Top Seller,UKAustraliaIndiaCanadaCanadaAustraliaAustralia...,85% Dark BarsMilk BarsFruit & Nut BarsAlmond C...,08-Jun-2214-Feb-2207-Jul-2224-Mar-2216-Jun-221...,216461,7074,30335928,223951.0
Dennison Crosswaite,Top Seller,New ZealandNew ZealandAustraliaAustraliaUKAust...,White ChocManuka Honey Choco70% Dark Bites85% ...,05-Jul-2215-Jun-2207-Feb-2205-Apr-2224-Mar-221...,291669,8767,54975977,238556.5
Dotty Strutley,Top Seller,AustraliaAustraliaUKUSAUKAustraliaUKAustraliaC...,Drinking CocoFruit & Nut BarsAlmond ChocoManuk...,19-Jul-2223-Aug-2228-Jul-2210-Aug-2203-Jan-221...,190624,6853,33557615,175266.0
Gigi Bohling,Top Seller,IndiaUSAUKCanadaNew ZealandNew ZealandUKUSAInd...,Peanut Butter CubesChoco Coated AlmondsAlmond ...,07-Jul-2202-Mar-2210-Jan-2228-Jan-2204-Apr-222...,232666,6303,32982670,228819.5
Gunar Cockshoot,Top Seller,AustraliaUSAAustraliaAustraliaUKAustraliaCanad...,After NinesSpicy Special SlimsFruit & Nut Bars...,24-Mar-2217-Feb-2215-Jun-2225-Jan-2227-Jun-221...,238483,6677,36728776,209345.5
Husein Augar,Top Seller,UKUSAUSAUKAustraliaNew ZealandUKUKAustraliaUSA...,Drinking CocoEclairsAfter NinesSpicy Special S...,14-Mar-2207-Jul-2208-Apr-2225-Aug-2228-Jun-222...,205212,5849,32629142,185003.0
Jan Morforth,Top Seller,AustraliaUSAIndiaIndiaIndiaAustraliaAustraliaI...,Peanut Butter CubesPeanut Butter CubesSpicy Sp...,27-Apr-2222-Jul-2212-Apr-2211-Mar-2205-Jan-222...,219667,7661,40815586,189871.5
Jehu Rudeforth,Top Seller,UKUKNew ZealandCanadaNew ZealandCanadaCanadaCa...,Mint Chip ChocoPeanut Butter Cubes50% Dark Bit...,04-Jan-2224-Feb-2220-Apr-2215-Jul-2211-Mar-221...,220976,7246,35490091,209345.5
Kaine Padly,Top Seller,AustraliaUSAAustraliaUKCanadaUSAAustraliaNew Z...,EclairsPeanut Butter CubesManuka Honey ChocoOr...,28-Feb-2216-Feb-2212-Jan-2231-Mar-2204-Jul-221...,266490,7253,39201911,219082.5
Karlen McCaffrey,Top Seller,New ZealandIndiaUKIndiaUSAIndiaUSACanadaNew Ze...,Drinking CocoFruit & Nut BarsAlmond ChocoManuk...,28-Jul-2226-Jan-2230-Jun-2204-Jul-2215-Apr-220...,223895,9658,48577354,228819.5
Kelci Walkden,Top Seller,New ZealandUSACanadaUKIndiaIndiaUKIndiaUSAAust...,After NinesAfter NinesBaker's Choco ChipsFruit...,07-Jul-2202-Jun-2226-May-2229-Jun-2219-Apr-220...,311710,8702,56791070,262899.0
Madelene Upcott,Top Seller,CanadaAustraliaIndiaAustraliaCanadaUSAUSAAustr...,Almond ChocoSpicy Special SlimsRaspberry Choco...,22-Aug-2207-Mar-2207-Jul-2205-Jan-2224-Jan-221...,316099,7279,49533337,219082.5
Mallorie Waber,Top Seller,CanadaCanadaAustraliaNew ZealandCanadaNew Zeal...,EclairsChoco Coated AlmondsMilk BarsManuka Hon...,13-Jan-2211-Jul-2229-Jul-2213-Apr-2220-Apr-222...,200592,5980,28119469,199608.5
Marney O'Breen,Top Seller,New ZealandUSAIndiaAustraliaUSAUSAUSAUSANew Ze...,Peanut Butter CubesAfter Nines85% Dark BarsOrg...,03-Aug-2230-May-2219-Jul-2216-May-2227-Jan-221...,259742,8043,40301037,219082.5
Oby Sorrel,Top Seller,UKIndiaIndiaIndiaCanadaIndiaUKNew ZealandUKAus...,99% Dark & Pure99% Dark & PureOrganic Choco Sy...,25-Jan-2227-May-2208-Jul-2214-Apr-2201-Aug-220...,316645,8608,52217599,238556.5
Rafaelita Blaksland,Top Seller,UKUKAustraliaNew ZealandNew ZealandIndiaIndiaU...,Smooth Sliky Salty99% Dark & PureDrinking Coco...,13-Jan-2229-Jun-2221-Feb-2207-Jun-2220-May-220...,210245,4297,27461000,165529.0
Roddy Speechley,Top Seller,USACanadaUSAIndiaCanadaNew ZealandCanadaNew Ze...,Smooth Sliky SaltySpicy Special SlimsManuka Ho...,05-Apr-2209-Feb-2222-Jul-2210-Jun-2213-Jul-222...,251062,6899,43858962,209345.5
Van Tuxwell,Top Seller,IndiaIndiaCanadaNew ZealandUSAAustraliaUKUKUSA...,85% Dark BarsSmooth Sliky SaltyOrganic Choco S...,01-Aug-2206-Jun-2214-Feb-2224-May-2213-Jan-221...,303149,6799,37099055,248293.5
Wilone O'Kielt,Top Seller,AustraliaAustraliaAustraliaAustraliaUSANew Zea...,Manuka Honey ChocoCaramel Stuffed BarsOrganic ...,11-May-2214-Apr-2207-Jul-2206-Apr-2225-Apr-220...,138523,4033,18105108,165529.0

7. Documentación
Documenta claramente cada paso del análisis, explicando qué se hizo y por qué se hizo.
Asegúrate de que el código sea legible y esté bien comentado